# "volume" is a default id!

[0]
type = "shortcut"
trigger = "Pause"
target = "volume"
action = "rotate"
args = [+0.05]

[1]
type = "shortcut"
trigger = "Scroll Lock"
target = "volume"
action = "rotate"
args = [-0.05]

[2]
type = "shortcut"
trigger = "Print Screen"
target = "volume"
action = "toggle"

[3]
type = "sound"
target = "volume"
path = ":/resource/mac/volume.wav"

[4]
type = "osd"
target = "volume"
skin = "mac_volume"
position = "bottom"
offset_x = 0
offset_y = -100

[mac_volume]
type = "skin"
background = ":/resource/mac/volume.png"
progress = ":/resource/mac/meter.png"
disabled = ":/resource/mac/mute.png"
x = 33
y = 165
units = 16


#[trayicon.volume_icon]
#target = "volume"
#overrides = "win_sound_icon"

#[trayevent.0]
#trigger = "Mouse Wheel Up"
#source = "volume_icon"
#target = "volume"
#action = "changeValue"
#arg = 0.05

#[win_hide_volume_osd.0]
# no params!







