# "volume" is a default id!

[vol_up]
type = "shortcut"
trigger = "Pause"
target = "volume"
action = "rotate"
args = [+0.05]

[vol_down]
type = "shortcut"
trigger = "Scroll Lock"
target = "volume"
action = "rotate"
args = [-0.05]

[mute]
type = "shortcut"
trigger = "Print Screen"
target = "volume"
action = "toggle"

[br_up]
type = "shortcut"
trigger = "Ctrl+Shift+Up"
target = "brightness"
action = "rotate"
args = [+0.05]

[br_down]
type = "shortcut"
trigger = "Ctrl+Shift+Down"
target = "brightness"
action = "rotate"
args = [-0.05]

[exit]
type = "shortcut"
trigger = "Ctrl+Alt+Shift+Q"
target = "app"
action = "exit"

[sfx]
type = "sound"
targets = ["volume", "brightness"]
path = ":/resource/mac/volume.wav"

[vol_osd]
type = "osd"
target = "volume"
skin = "mac_volume"
position = "bottom"
offset_x = 0
offset_y = -100

[br_osd]
type = "osd"
target = "brightness"
skin = "mac_brightness"
position = "bottom"
offset_x = 0
offset_y = -100

[mac_volume]
type = "horizontal_bar_skin"
background = ":/resource/mac/volume.png"
progress = ":/resource/mac/meter.png"
disabled = ":/resource/mac/mute.png"
x = 33
y = 165
units = 16

[mac_brightness]
type = "horizontal_bar_skin"
background = ":/resource/mac/brightness.png"
progress = ":/resource/mac/meter.png"
disabled = ":/resource/mac/brightness.png"
x = 33
y = 165
units = 16

[br_icon]
type = "tray_icon"
target = "brightness"
skin = "mac_brightness"
#overrides = "win_sound_icon"

#[trayevent.0]
#trigger = "Mouse Wheel Up"
#source = "volume_icon"
#target = "volume"
#action = "changeValue"
#arg = 0.05

#[win_hide_volume_osd.0]
# no params!







