# "volume" is a default id!

[0]
type = "shortcut"
trigger = "Ctrl+Shift+1"
target = "volume"
action = "changeValue"
args = [-0.05]

[1]
type = "shortcut"
trigger = "Ctrl+Shift+3"
target = "volume"
action = "changeValue"
args = [0.05]

#[0]
#target = "volume" # type derived from id -- which is a knob!
#skin = "osd_mac_volume.toml"

#[sound.0]
#target = "volume"
#sound = "mac_volume.wav"

#[trayicon.volume_icon]
#target = "volume"
#overrides = "win_sound_icon"

#[trayevent.0]
#trigger = "Mouse Wheel Up"
#source = "volume_icon"
#target = "volume"
#action = "changeValue"
#arg = 0.05

#[win_hide_volume_osd.0]
# no params!







