# "volume" is a default id!

[volume_knob]
type = "knob"
step = 0.05
target = "volume"

[brightness_knob]
type = "knob"
step = 0.05
target = "brightness"

[volume_up_shortcut]
type = "shortcut"
trigger = "Pause"
target = "volume_knob"
action = "increase"

[volume_down_shortcut]
type = "shortcut"
trigger = "Scroll Lock"
target = "volume_knob"
action = "decrease"

[mute_shortcut]
type = "shortcut"
trigger = "Print Screen"
target = "volume_knob"
action = "toggle"

[brightness_up_shortcut]
type = "shortcut"
trigger = "Ctrl+Shift+Up"
target = "brightness_knob"
action = "increase"

[brightness_down_shortcut]
type = "shortcut"
trigger = "Ctrl+Shift+Down"
target = "brightness_knob"
action = "decrease"

[exit_shortcut]
type = "shortcut"
trigger = "Ctrl+Alt+Shift+Q"
target = "app"
action = "exit"

[volume_sound]
type = "sound"
target = "volume"
path = ":/resource/mac/volume.wav"

[volume_osd]
type = "osd"
target = "volume"
skin = "volume_skin"
position = "bottom"
offset_x = 0
offset_y = -100

[brightness_osd]
type = "osd"
target = "brightness"
skin = "brightness_skin"
position = "bottom"
offset_x = 0
offset_y = -100

[volume_skin]
type = "horizontal_bar_skin"
background = ":/resource/mac/volume.png"
progress = ":/resource/mac/meter.png"
disabled = ":/resource/mac/mute.png"
x = 33
y = 165
units = 16

[brightness_skin]
type = "horizontal_bar_skin"
background = ":/resource/mac/brightness.png"
progress = ":/resource/mac/meter.png"
disabled = ":/resource/mac/brightness.png"
x = 33
y = 165
units = 16

[tray_icon_skin]
type = "numeric_skin"
color = "red"

[brightness_icon]
type = "tray_icon"
target = "brightness"
skin = "tray_icon_skin"
#overrides = "win_sound_icon"

#[]
#type = "tray_event"
#trigger = "MWHEELUP"
#source = "brightness_icon"
#target = "brightness_knob"
#action = "rotateUp"

#[]
#type = "hide_win10_volume_osd"






