# "volume" is a default id!

[volume_knob]
type = "knob"
step = 0.05
target = "volume"

[precise_volume_knob]
type = "knob"
step = 0.01
target = "volume"

[brightness_knob]
type = "knob"
step = 0.05
target = "brightness"

[precise_brightness_knob]
type = "knob"
step = 0.01
target = "brightness"

[volume_up_hotkey]
type = "hotkey"
trigger = "Pause"
target = "volume_knob"
action = "increase"

[volume_down_hotkey]
type = "hotkey"
trigger = "Scroll Lock"
target = "volume_knob"
action = "decrease"

[mute_hotkey]
type = "hotkey"
trigger = "Print Screen"
target = "volume_knob"
action = "toggle"

[brightness_up_hotkey]
type = "hotkey"
trigger = "Ctrl+Shift+Up"
target = "brightness_knob"
action = "increase"

[brightness_down_hotkey]
type = "hotkey"
trigger = "Ctrl+Shift+Down"
target = "brightness_knob"
action = "decrease"

[exit_hotkey]
type = "hotkey"
trigger = "Ctrl+Alt+Shift+Q"
target = "app"
action = "exit"

[debug_hotkey]
type = "hotkey"
trigger = "Ctrl+Alt+Shift+D"
target = "app"
action = "debugAction"

[volume_sound]
type = "sound"
target = "volume"
path = ":/resource/mac/volume.wav"

[volume_osd]
type = "osd"
target = "volume"
skin = "volume_skin"
position = "bottom"
offset = [0, -100]

[brightness_osd]
type = "osd"
target = "brightness"
skin = "brightness_skin"
position = "bottom"
offset = [0, -100]

[volume_skin]
type = "horizontal_bar_skin"
background = ":/resource/mac/volume.png"
progress = ":/resource/mac/meter.png"
disabled = ":/resource/mac/mute.png"
x = 33
y = 165
units = 16

[brightness_skin]
type = "horizontal_bar_skin"
background = ":/resource/mac/brightness.png"
progress = ":/resource/mac/meter.png"
disabled = ":/resource/mac/brightness.png"
x = 33
y = 165
units = 16

[tray_icon_skin]
type = "numeric_skin"
color = "white"
font = "Consolas"

[brightness_icon]
type = "tray_icon"
target = "brightness"
skin = "tray_icon_skin"

[volume_up_tray_event]
type = "tray_event"
trigger = "mwheelup"
source = "volume_icon"
target = "volume_knob"
action = "increase"

[volume_down_tray_event]
type = "tray_event"
trigger = "mwheeldown"
source = "volume_icon"
target = "volume_knob"
action = "decrease"

[precise_volume_up_tray_event]
type = "tray_event"
trigger = "alt+mwheelup"
source = "volume_icon"
target = "precise_volume_knob"
action = "increase"

[precise_volume_down_tray_event]
type = "tray_event"
trigger = "alt+mwheeldown"
source = "volume_icon"
target = "precise_volume_knob"
action = "decrease"

[brightness_up_tray_event]
type = "tray_event"
trigger = "mwheelup"
source = "brightness_icon"
target = "brightness_knob"
action = "increase"

[brightness_down_tray_event]
type = "tray_event"
trigger = "mwheeldown"
source = "brightness_icon"
target = "brightness_knob"
action = "decrease"

[precise_brightness_up_tray_event]
type = "tray_event"
trigger = "alt+mwheelup"
source = "brightness_icon"
target = "precise_brightness_knob"
action = "increase"

[precise_brightness_down_tray_event]
type = "tray_event"
trigger = "alt+mwheeldown"
source = "brightness_icon"
target = "precise_brightness_knob"
action = "decrease"

[win10]
type = "win10"
hide_native_osd = true
hide_console = true

[emdash_hotkey]
type = "hotkey"
trigger = "Ctrl+Alt+-"
target = "keyboard"
action = "type"
args = ["—"]

