# "volume" is a default id!

[0]
type = "shortcut"
trigger = "Ctrl+Shift+1"
target = "volume"
action = "rotate"
args = [-0.05]

[1]
type = "shortcut"
trigger = "Ctrl+Shift+3"
target = "volume"
action = "rotate"
args = [0.05]

[2]
type = "sound"
target = "volume"
path = "resource/mac/volume.wav"

[3]
type = "osd"
target = "volume" # type derived from id -- which is a knob!
skin = "mac_volume"

[mac_volume]
type = "skin"
background = "resource/mac/volume.png"
progress = "resource/mac/meter.png"
disabled = "resource/mac/mute.png"
x = 33
y = 165
units = 16


#[trayicon.volume_icon]
#target = "volume"
#overrides = "win_sound_icon"

#[trayevent.0]
#trigger = "Mouse Wheel Up"
#source = "volume_icon"
#target = "volume"
#action = "changeValue"
#arg = 0.05

#[win_hide_volume_osd.0]
# no params!







