#pragma once

#include <QtCore/QKeyCombination>

#include "key_mouse.h"

struct KeyTableElement {
    QKeyCombination key;
    const char* name;
};

constexpr KeyTableElement KeyTable = {
    { Qt::Key_Mouse1,                           "Mouse1" },
    { Qt::Key_Mouse2,                           "Mouse2" },
    { Qt::Key_Mouse3,                           "Mouse3" },
    { Qt::Key_WheelUp,                          "MWheelUp" },
    { Qt::Key_WheelDown,                        "MWheelDown" },
    { Qt::Key_Backspace,                        "Backspace" },
    { Qt::Key_Tab,                              "Tab" },
    { Qt::Key_Clear | Qt::KeypadModifier,       "Clear" },
    { Qt::Key_Return,                           "Enter" },
    { Qt::Key_Return,                           "Return" },
    { Qt::Key_Shift,                            "Shift" },
    { Qt::Key_Control,                          "Ctrl" },
    { Qt::Key_Alt,                              "Alt" },
    { Qt::Key_Pause,                            "Pause" },
    { Qt::Key_CapsLock,                         "CapsLock" },
    { Qt::Key_CapsLock,                         "Caps Lock" },
    { Qt::Key_Escape,                           "Esc" },
    { Qt::Key_Escape,                           "Escape" },
    { Qt::Key_Space,                            "Space" },
    { Qt::Key_PageUp,                           "PgUp" },
    { Qt::Key_PageUp,                           "PageUp" },
    { Qt::Key_PageUp,                           "Page Up" },
    { Qt::Key_PageDown,                         "PgDn" },
    { Qt::Key_PageDown,                         "PageDown" },
    { Qt::Key_PageDown,                         "Page Down" },
    { Qt::Key_End,                              "End" },
    { Qt::Key_Home,                             "Home" },
    { Qt::Key_Left,                             "Left" },
    { Qt::Key_Left,                             "LeftArrow" },
    { Qt::Key_Up,                               "Up" },
    { Qt::Key_Up,                               "UpArrow" },
    { Qt::Key_Right,                            "Right" },
    { Qt::Key_Right,                            "RightArrow" },
    { Qt::Key_Down,                             "Down" },
    { Qt::Key_Down,                             "DownArrow" },
    { Qt::Key_Print,                            "PrintScreen" },
    { Qt::Key_Print,                            "Print Screen" },
    { Qt::Key_Insert,                           "Ins" },
    { Qt::Key_Insert,                           "Insert" },
    { Qt::Key_Delete,                           "Del" },
    { Qt::Key_Delete,                           "Delete" },
    { Qt::Key_Help,                             "Help" },
    { Qt::Key_0,                                "0" },
    { Qt::Key_1,                                "1" },
    { Qt::Key_2,                                "2" },
    { Qt::Key_3,                                "3" },
    { Qt::Key_4,                                "4" },
    { Qt::Key_5,                                "5" },
    { Qt::Key_6,                                "6" },
    { Qt::Key_7,                                "7" },
    { Qt::Key_8,                                "8" },
    { Qt::Key_9,                                "9" },
    { Qt::Key_A,                                "A" },
    { Qt::Key_B,                                "B" },
    { Qt::Key_C,                                "C" },
    { Qt::Key_D,                                "D" },
    { Qt::Key_E,                                "E" },
    { Qt::Key_F,                                "F" },
    { Qt::Key_G,                                "G" },
    { Qt::Key_H,                                "H" },
    { Qt::Key_I,                                "I" },
    { Qt::Key_J,                                "J" },
    { Qt::Key_K,                                "K" },
    { Qt::Key_L,                                "L" },
    { Qt::Key_M,                                "M" },
    { Qt::Key_N,                                "N" },
    { Qt::Key_O,                                "O" },
    { Qt::Key_P,                                "P" },
    { Qt::Key_Q,                                "Q" },
    { Qt::Key_R,                                "R" },
    { Qt::Key_S,                                "S" },
    { Qt::Key_T,                                "T" },
    { Qt::Key_U,                                "U" },
    { Qt::Key_V,                                "V" },
    { Qt::Key_W,                                "W" },
    { Qt::Key_X,                                "X" },
    { Qt::Key_Y,                                "Y" },
    { Qt::Key_Z,                                "Z" },
    { Qt::Key_Meta,                             "Win" },
    { Qt::Key_Menu,                             "Menu" },
    { Qt::Key_Menu,                             "Apps" },
    { Qt::Key_0 | Qt::KeypadModifier,           "Num0" },
    { Qt::Key_1 | Qt::KeypadModifier,           "Num1" },
    { Qt::Key_2 | Qt::KeypadModifier,           "Num2" },
    { Qt::Key_3 | Qt::KeypadModifier,           "Num3" },
    { Qt::Key_4 | Qt::KeypadModifier,           "Num4" },
    { Qt::Key_5 | Qt::KeypadModifier,           "Num5" },
    { Qt::Key_6 | Qt::KeypadModifier,           "Num6" },
    { Qt::Key_7 | Qt::KeypadModifier,           "Num7" },
    { Qt::Key_8 | Qt::KeypadModifier,           "Num8" },
    { Qt::Key_9 | Qt::KeypadModifier,           "Num9" },
    { Qt::Key_Asterisk | Qt::KeypadModifier,    "Num*" },
    { Qt::Key_Plus | Qt::KeypadModifier,        "Num+" },
    { Qt::Key_Minus | Qt::KeypadModifier,       "Num-" },
    { Qt::Key_Period | Qt::KeypadModifier,      "Num." },
    { Qt::Key_Slash | Qt::KeypadModifier,       "Num/" },
    { Qt::Key_F1,                               "F1" },
    { Qt::Key_F2,                               "F2" },
    { Qt::Key_F3,                               "F3" },
    { Qt::Key_F4,                               "F4" },
    { Qt::Key_F5,                               "F5" },
    { Qt::Key_F6,                               "F6" },
    { Qt::Key_F7,                               "F7" },
    { Qt::Key_F8,                               "F8" },
    { Qt::Key_F9,                               "F9" },
    { Qt::Key_F10,                              "F10" },
    { Qt::Key_F11,                              "F11" },
    { Qt::Key_F12,                              "F12" },
    { Qt::Key_F13,                              "F13" },
    { Qt::Key_F14,                              "F14" },
    { Qt::Key_F15,                              "F15" },
    { Qt::Key_F16,                              "F16" },
    { Qt::Key_F17,                              "F17" },
    { Qt::Key_F18,                              "F18" },
    { Qt::Key_F19,                              "F19" },
    { Qt::Key_F20,                              "F20" },
    { Qt::Key_F21,                              "F21" },
    { Qt::Key_F22,                              "F22" },
    { Qt::Key_F23,                              "F23" },
    { Qt::Key_F24,                              "F24" },
    { Qt::Key_NumLock | Qt::KeypadModifier,     "NumLock" },
    { Qt::Key_NumLock | Qt::KeypadModifier,     "Num Lock" },
    { Qt::Key_ScrollLock,                       "ScrollLock" },
    { Qt::Key_ScrollLock,                       "Scroll Lock" },
    { Qt::Key_Back,                             "Back" },
    { Qt::Key_Forward,                          "Forward" },
    { Qt::Key_Refresh,                          "Refresh" },
    { Qt::Key_Search,                           "Search" },
    { Qt::Key_Favorites,                        "Favorites" },
    { Qt::Key_HomePage,                         "HomePage" },
    { Qt::Key_HomePage,                         "Home Page" },
    { Qt::Key_VolumeMute,                       "Mute" },
    { Qt::Key_VolumeMute,                       "Volume Mute" },
    { Qt::Key_VolumeDown,                       "Vol-" },
    { Qt::Key_VolumeDown,                       "Volume Down" },
    { Qt::Key_VolumeUp,                         "Vol+" },
    { Qt::Key_VolumeUp,                         "Volume Up" },
    { Qt::Key_MediaNext,                        "NextTrack" },
    { Qt::Key_MediaNext,                        "Next Track" },
    { Qt::Key_MediaPrevious,                    "PreviousTrack" },
    { Qt::Key_MediaPrevious,                    "Previous Track" },
    { Qt::Key_MediaStop,                        "Stop" },
    { Qt::Key_MediaPlay,                        "Play" },
    { Qt::Key_MediaPlay,                        "Play/Pause" },
    { Qt::Key_LaunchMail,                       "Mail" },
    { Qt::Key_LaunchMail,                       "Launch Mail" },
    { Qt::Key_LaunchMedia,                      "Media" },
    { Qt::Key_LaunchMedia,                      "Launch Media" },
    { Qt::Key_Launch0,                          "App1" },
    { Qt::Key_Launch1,                          "App2" },
    { Qt::Key_Semicolon,                        ";" },
    { Qt::Key_Semicolon,                        "Semicolon" },
    { Qt::Key_Equal,                            "=" },
    { Qt::Key_Comma,                            "," },
    { Qt::Key_Minus,                            "-" },
    { Qt::Key_Period,                           "." },
    { Qt::Key_Slash,                            "/" },
    { Qt::Key_QuoteLeft,                        "`" },
    { Qt::Key_BracketLeft,                      "[" },
    { Qt::Key_Backslash,                        "\\" },
    { Qt::Key_BracketRight,                     "]" },
    { Qt::Key_Apostrophe,                       "'" },
    { Qt::Key_Zoom,                             "Zoom" },
    { Qt::Key_unknown,                          nullptr }
};
