name: build

on:
  pull_request: null
  workflow_dispatch:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
        architecture:
          - x86_64
    steps:
      # Checkout Code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: '${{inputs.myCommit}}'

      # Setup the MSVC build enviroment
      - name: Setup environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: '${{matrix.architecture}}'

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.3.0'
          modules: 'qtmultimedia'
          archives: 'qtbase'
          cache: 'true'

      # Restore ccache file from cache if possible so we don't have to download it.
      - name: Restore cached ccache
        id: ccache-cache
        uses: actions/cache/restore@v3
        with:
          path: 'C:\ProgramData\chocolatey\lib\ccache\'
          key: windows-ccache

      # Chocolatey uses shims so create the shim if we used the cached ccache exe
      - name: Add ccache shim
        if: steps.ccache-cache.outputs.cache-hit == 'true'
        run: |
          C:\ProgramData\chocolatey\tools\shimgen.exe -o=C:\ProgramData\chocolatey\bin\ccache.exe -p=C:\ProgramData\chocolatey\lib\ccache\tools\ccache-4.8.2-windows-x86_64\ccache.exe

      # If ccache can't be restored from cache upgrade it
      - name: Update ccache
        if: steps.ccache-cache.outputs.cache-hit != 'true'
        run: |
          choco upgrade ccache --version=4.8.2

      # If ccache can't be restored from cache after upgrade cache it
      - name: Save ccache to cache
        if: steps.ccache-cache.outputs.cache-hit != 'true'
        id: check-for-ccache-save
        uses: actions/cache/save@v3
        with:
          path: 'C:\ProgramData\chocolatey\lib\ccache\'
          key: windows-ccache

      # GH action for ccache, only save cache if its on master branch or has a release build tag
      - name: Run ccache
        uses: hendrikmuhs/ccache-action@v1.2.10
        with:
          key: 'windows-${{matrix.configuration}}-${{matrix.architecture}}'
          save: ${{ github.ref == 'refs/heads/master' || inputs.releaseTag != '' }}
          verbose: 2
          max-size: 250M

      # MSVC hit rate is higher with ignoring the hash_dir and is safe
      - name: Set ccache config values
        run: |
          ccache --set-config=hash_dir=false
          ccache --set-config=compiler_check=none

      - name: Configure
        run: |
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{matrix.configuration}}

      - name: Build
        working-directory: build
        shell: cmd
        run: |
          ninja -v

      - name: Run tests
        working-directory: build
        run: |
          ninja run_qnob_test

      - name: Check dependencies
        run: |
          dumpbin /imports build\qnob.exe

      - name: Cleanup ccache
        run: |
          ccache -c
